export const VIDEO_FIELDS = {
  TITLE: 'vod_name',
  ALIAS: 'vod_alias',
  SURFACE_PLOT: 'vod_surface_plot',
  DIRECTORS: 'vod_directors',
  ACTORS: 'vod_actors',
  STATUS: 'vod_status',
  END: 'vod_isEnd',
  INTRODUCE: 'vod_introduce',
  NUMBER: 'vod_number',
  TRAILER_TIME: 'vod_release_time',
  SHELF_AT: 'vod_shelf_time',
  DURATION: 'vod_duration',
  IMDB_SCORE: 'vod_imdb_score',
  DOUBAN_SCORE: 'vod_douban_score',
  UNIT: 'vod_unit',
  LANGUAGE: 'vod_lang',
  REGION: 'vod_area',
  YEAR: 'vod_year',
  HORIZONTAL_POSTER: 'vod_pic_thumb',
  VERTICAL_POSTER: 'vod_vertical_poster',
  NOTE: 'vod_note',
  CYCLE: 'vod_cycle',
  TOTAL: 'vod_total',
  CATEGORY_ID: 'vod_type_id',
};
